[package]
name = "murmel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.8.0"
deno_core = "0.153.0"
serde = { version = "1.0", features = ["derive"] }